input_text <- readFile("../data/gundam_and_math/")

input_text <- readFile("../data/anime/")
input_text <- clean(input_text, sw = c("relea", "includ", "+", "-", "/"))
lda <- top_terms_by_topic_LDA(input_text, number_of_topics = 10, plot = F)

input_text <- readFile("../data/math")

top_terms_by_topic_LDA(input_text, number_of_topics = 2, plot = T)
lda <- top_terms_by_topic_LDA(input_text, number_of_topics = 2, plot = F)
top_terms_by_topic_LDA(input_text, number_of_topics = 2, user_alpha = 6.30908)
top_terms_by_topic_LDA(input_text, user_model = lda)

k2 <- top_terms_by_topic_LDA(input_text, number_of_topics = 2, plot = F)
k3 <- top_terms_by_topic_LDA(input_text, number_of_topics = 3, plot = F)
k4 <- top_terms_by_topic_LDA(input_text, number_of_topics = 4, plot = F)
k5 <- top_terms_by_topic_LDA(input_text, number_of_topics = 5, plot = F)
k6 <- top_terms_by_topic_LDA(input_text, number_of_topics = 6, plot = F)
k7 <- top_terms_by_topic_LDA(input_text, number_of_topics = 7, plot = F)
k8 <- top_terms_by_topic_LDA(input_text, number_of_topics = 8, plot = F)
k9 <- top_terms_by_topic_LDA(input_text, number_of_topics = 9, plot = F)
k10 <- top_terms_by_topic_LDA(input_text, number_of_topics = 10, plot = F)

top_terms_by_topic_LDA(input_text, user_model = k2)
top_terms_by_topic_LDA(input_text, user_model = k3)
top_terms_by_topic_LDA(input_text, user_model = k4)
top_terms_by_topic_LDA(input_text, user_model = k5)
top_terms_by_topic_LDA(input_text, user_model = k6)
top_terms_by_topic_LDA(input_text, user_model = k7)
top_terms_by_topic_LDA(input_text, user_model = k8)
top_terms_by_topic_LDA(input_text, user_model = k9)
top_terms_by_topic_LDA(input_text, user_model = k10)

top_terms_by_topic_LDA(input_text, number_of_topics = 2)
top_terms_by_topic_LDA(input_text, number_of_topics = 3)
top_terms_by_topic_LDA(input_text, number_of_topics = 4)
top_terms_by_topic_LDA(input_text, number_of_topics = 5)
top_terms_by_topic_LDA(input_text, number_of_topics = 6)
top_terms_by_topic_LDA(input_text, number_of_topics = 7)
top_terms_by_topic_LDA(input_text, number_of_topics = 8)
top_terms_by_topic_LDA(input_text, number_of_topics = 9)
top_terms_by_topic_LDA(input_text, number_of_topics = 10)